# -*- coding: utf-8 -*-
"""Task 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JqjEq6BiQuOoHyOqqRIhPQrxOI4SkcXv
"""

import numpy as np

import pandas as pd

import os

import seaborn as sns

import matplotlib.pyplot as plt

from sklearn import svm

from sklearn.metrics import accuracy_score

from sklearn.neighbors import KNeighborsClassifier

from sklearn import metrics

from sklearn.model_selection import cross_val_score

from sklearn import preprocessing

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler

import joblib

from sklearn.metrics import accuracy_score

df = pd.read_csv(r"/content/collegePlace.csv")
df.head()



df.info()



df.isnull().sum()

def transformationplot(feature):

  plt.figure(figsize=(12,5)) 
  plt.subplot(1,2,1) 
  sns.distplot(feature)

  transformationplot(np.log(df['Age']))

df = df.replace(['Male'], [8])

df = df.replace(['Female'], [1])

df = df.replace(['Computer Science', 'Information Technology', 'Electronics And Communication', 'Mechanical', 'Electrical', 'Civil'], [0,1,2,3,4,5])

df = df.drop(['Hostel'], axis=1)

df